CREATE TABLE Colegio (
    id_colegio INT PRIMARY KEY AUTO_INCREMENT,

    id_comuna INT NOT NULL,
    FOREIGN KEY (id_comuna)
        REFERENCES Comuna(id_comuna) ON DELETE RESTRICT,
    id_region INT NOT NULL,
    FOREIGN KEY (id_region)
        REFERENCES Region(id_region) ON DELETE RESTRICT,
    id_direccion INT NOT NULL,
    FOREIGN KEY (id_direccion)
        REFERENCES Direccion(id_direccion) ON DELETE RESTRICT,

    rbd VARCHAR(10) UNIQUE, /* Codigo Mineduc */
    nombre VARCHAR(200) NOT NULL,
    tipo_colegio ENUM ('GRATUITOS', 'SUBVENCIONADOS DE FINANCIAMIENTO COMPARTIDO', 'ADMINISTRACIÓN DELEGADA', "PARTICULARES PAGADOS", 'PARTICULARES SUBVENCIONADOS',  "CIENTIFICO HUMANISTA", "TECNICO") NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (nombre, id_comuna)
)