CREATE_TABLE PREREQUISITOS(
    id_prerequisito INT PRIMARY KEY AUTO_INCREMENT,

    id_ramo INT NOT NULL,
    FOREIGN KEY (id_ramo) REFERENCES Ramo(id_ramo) ON DELETE CASCADE,

    tipo_prerequisito ENUM('OBLIGATORIO', 'OPTATIVO', "RECOMENDADO", "CORREQUISITO") NOT NULL
)