CREATE TABLE Region (
    id_region INT PRIMARY KEY AUTO_INCREMENT,
    
    codigo INT UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL UNIQUE,

    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)